language: rust

rust:
  - 1.42.0

cache:
  cargo: true

env:
  - BITCOIN_EXE_DIR=$TRAVIS_BUILD_DIR/bitcoin-0.19.1/bin

before_install:
  - curl https://bitcoincore.org/bin/bitcoin-core-0.19.1/bitcoin-0.19.1-x86_64-linux-gnu.tar.gz | tar -xvz

script:
  - cargo build --verbose --all
  - cargo test --verbose --all