language: rust
cache: cargo

before_script:
  - |
    if [[ -z "$TARGET" ]]; then
      rustup target install $TARGET
      curl -o $NDK_VER-$HOST.zip https://dl.google.com/android/repository/$NDK_VER-$HOST.zip && unzip -q $NDK_VER-$HOST.zip $NDK_VER/toolchains/llvm/prebuilt/*
    else
      curl https://bitcoincore.org/bin/bitcoin-core-$BITCOIN_VER/bitcoin-$BITCOIN_VER-x86_64-linux-gnu.tar.gz | tar -xvz bitcoin-$BITCOIN_VER/bin/bitcoind
    fi

matrix:
  include:
    - rust: 1.38.0
    - rust: stable
    - rust: nightly
    - rust: stable
      env: TARGET=i686-linux-android
      script:
        - cd lib && ./build-android/x86.sh
    - rust: stable
      env: TARGET=x86_64-linux-android
      script:
        - cd lib && ./build-android/x86_64.sh
    - rust: stable
      env: TARGET=armv7-linux-androideabi
      script:
        - cd lib && ./build-android/armv7a.sh
    - rust: stable
      env: TARGET=aarch64-linux-android
      script:
        - cd lib && ./build-android/arm64-v8a.sh
  allow_failures:
    - rust: nightly

env:
  global:
    - BITCOIN_VER=0.20.1
    - BITCOIN_EXE_DIR=$TRAVIS_BUILD_DIR/bitcoin-$BITCOIN_VER/bin
    - NDK_VER=android-ndk-r21d
    - NDK=$TRAVIS_BUILD_DIR/$NDK_VER
    - HOST=linux-x86_64

