language: rust
cache: cargo

matrix:
  include:
    - rust: 1.38.0
      script:
        - cargo build --verbose --all
        - curl https://bitcoincore.org/bin/bitcoin-core-$BITCOIN_VER/bitcoin-$BITCOIN_VER-x86_64-linux-gnu.tar.gz | tar -xvz
        - cargo test --verbose --all
    - rust: stable
      script:
        - cargo build --verbose --all
        - curl https://bitcoincore.org/bin/bitcoin-core-$BITCOIN_VER/bitcoin-$BITCOIN_VER-x86_64-linux-gnu.tar.gz | tar -xvz
        - cargo test --verbose --all
    - rust: nightly
      script:
        - cargo build --verbose --all
        - curl https://bitcoincore.org/bin/bitcoin-core-$BITCOIN_VER/bitcoin-$BITCOIN_VER-x86_64-linux-gnu.tar.gz | tar -xvz
        - cargo test --verbose --all
    - rust: stable
      env: TARGET=i686-linux-android
      script:
        - rustup target install $TARGET
        - curl -o android-ndk-r21c-linux-x86_64.zip https://dl.google.com/android/repository/android-ndk-r21c-linux-x86_64.zip && unzip -q android-ndk-r21c-linux-x86_64.zip
        - cd lib && ./build-android/x86.sh
    - rust: stable
      env: TARGET=x86_64-linux-android
      script:
        - rustup target install $TARGET
        - curl -o android-ndk-r21c-linux-x86_64.zip https://dl.google.com/android/repository/android-ndk-r21c-linux-x86_64.zip && unzip -q android-ndk-r21c-linux-x86_64.zip
        - cd lib && ./build-android/x86_64.sh
    - rust: stable
      env: TARGET=armv7-linux-androideabi
      script:
        - rustup target install $TARGET
        - curl -o android-ndk-r21c-linux-x86_64.zip https://dl.google.com/android/repository/android-ndk-r21c-linux-x86_64.zip && unzip -q android-ndk-r21c-linux-x86_64.zip
        - cd lib && ./build-android/armv7a.sh
    - rust: stable
      env: TARGET=aarch64-linux-android
      script:
        - rustup target install $TARGET
        - curl -o android-ndk-r21c-linux-x86_64.zip https://dl.google.com/android/repository/android-ndk-r21c-linux-x86_64.zip && unzip -q android-ndk-r21c-linux-x86_64.zip
        - cd lib && ./build-android/arm64-v8a.sh
  allow_failures:
    - rust: nightly

env:
  global:
    - BITCOIN_VER=0.20.1
    - BITCOIN_EXE_DIR=$TRAVIS_BUILD_DIR/bitcoin-$BITCOIN_VER/bin
    - NDK=$TRAVIS_BUILD_DIR/android-ndk-r21c
    - HOST=linux-x86_64

