language: rust

rust:
  - 1.42.0

cache:
  cargo: true
  directories:
    - $TRAVIS_BUILD_DIR/bitcoin/

env:
  - BITCOIN_EXE_DIR=$TRAVIS_BUILD_DIR/bitcoin/bitcoin-0.19.1/bin

before_install: |
  if ! [ -f ./bitcoin/bitcoin-0.19.1-x86_64-linux-gnu.tar.gz ]; then
    curl https://bitcoincore.org/bin/bitcoin-core-0.19.1/bitcoin-0.19.1-x86_64-linux-gnu.tar.gz -o ./bitcoin/bitcoin-0.19.1-x86_64-linux-gnu.tar.gz;
    cd bitcoin
    cat bitcoin-0.19.1-x86_64-linux-gnu.tar.gz | gzip -d | tar -xv
  fi

script:
  - cargo build --verbose --all
  - cargo test --verbose --all